# Generated by Django 5.0.7 on 2024-07-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='day_number',
            field=models.IntegerField(default=1),
        ),
    ]
