# Generated by Django 5.0.7 on 2024-07-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_day_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscleinformation',
            name='muscle_group',
            field=models.CharField(choices=[('BACK', 'Upper back'), ('SHOULDER', 'Shoulder/clavicle'), ('ARM', 'Arm/elbow'), ('HAND', 'Wrist/hand'), ('LOWER_BACK', 'Lower back'), ('HIP', 'Hip/pelvis'), ('KNEE', 'Thigh/Knee'), ('ARTHRITIS', 'Arthritis')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='muscleinformation',
            unique_together={('client', 'muscle_group', 'date')},
        ),
    ]
