# Generated by Django 5.0.7 on 2024-07-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_muscleinformation_muscle_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('client', 'date')},
        ),
    ]
