# Generated by Django 5.0.7 on 2024-07-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_absence_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='day_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('exercise_name', 'training_plan')},
        ),
        migrations.AlterUniqueTogether(
            name='fitnessassessment',
            unique_together={('client', 'date')},
        ),
    ]
