# Generated by Django 5.0.7 on 2024-07-17 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_client_date_joined_client_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id_number',
        ),
        migrations.AlterField(
            model_name='client',
            name='work_phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
    ]
