# Generated by Django 5.0.7 on 2024-07-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_remove_client_id_number_alter_client_work_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientimage',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fitnessassessment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='muscleinformation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
