# Generated by Django 5.0.7 on 2024-07-18 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_absence_date_alter_clientimage_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('Female', 'Female')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_end_data',
            field=models.DateField(default=datetime.datetime(2024, 7, 18, 11, 52, 3, 298429, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_plan',
            field=models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY'), ('DAILY', 'DAILY')], default='Monthly', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_start_data',
            field=models.DateField(default=datetime.datetime(2024, 7, 18, 11, 52, 23, 230947, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
